name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - refactor_bench_summary

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the main branch
        uses: actions/checkout@v4

      - name: checkout the bench_data branch to a given folder
        uses: actions/checkout@v4
        with:
          ref: 'bench_data'
          sparse-checkout: |
            data.json
          sparse-checkout-cone-mode: false
          path: 'benchmark_data'

      - name: print the content of the file from the bench_data branch
        run: cat benchmark_data/data.json

      - name: evaluate benchmark
        uses: ./
        id: eval
        with:
          name: "Benchmark"
          folder_with_bench_data: ./benchmark_data
          file_with_bench_data: data.json
          bench_to_compare: "Benchmark"
          current_bench_res_file: ./benchmark_results/curr.json
          evaluation_method: threshold
          threshold_values: 100, 400, 600
          comparison_operators: smaller, bigger, tolerance
          comparison_margins: 10, 10, 10
          action_page_job_summary: on
          failing_condition: any
          comment_to_commit: on
          save_curr_bench_res: true
          github_token: ${{ secrets.GH_TOKEN }}

      - name: print the content of the data file after the update
        run: cat benchmark_data/data.json

      - name: Commit files
        working-directory: ./benchmark_data
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
          git push origin bench_data

      - name: Check output and fail if needed
        if: steps.eval.outputs.should_fail == 'true'
        run: |
          echo "Failing as indicated by evaluation action"
          exit 1
          
          

#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GH_TOKEN }}
#        branch: bench_data

